### ISSUE TITLE
cli, selecting another engine just uses pandas anyway

### ISSUE THREAD

**Issue by jopietsch** [netenglabs/suzieq#11]
we should remove the option to filter by engine

jpiet> system show engine=foop
     datacenter         hostname model      version   vendor architecture status          address                     uptime               timestamp
5          dual  192.168.121.113                                            dead                  18289 days 20:31:24.672000 2020-01-28 20:31:24.672
6          dual  192.168.121.119                                            dead                  18289 days 21:08:32.896000 2020-01-28 21:08:32.896
10         dual  192.168.121.146                                            dead                  18289 days 20:31:24.672000 2020-01-28 20:31:24.672
13         dual  192.168.121.171                                            dead                  18289 days 21:08:32.896000 2020-01-28 21:08:32.896
15         dual  192.168.121.175                                            dead                  18289 days 21:26:01.472000 2020-01-28 21:26:01.472
17         dual  192.168.121.199                                            dead                  18289 days 21:26:01.472000 2020-01-28 21:26:01.472
20         dual  192.168.121.250                                            dead

**Comment by ddutt** [comment]
Closing as this issue is irrelevant for now
