### ISSUE TITLE
add route summarize with prefixlen filter

### ISSUE THREAD

**Issue by jopietsch** [netenglabs/suzieq#114]
**Is your feature request related to a problem? Please describe.**
 I'd like to be able to filter route summarization by prefixlen (or perhaps other filters)

```
jpiet> route summarize  namespace=single-attach_bgp_numbered prefixlen='<=16'
Unknown argument(s) ['prefixlen'] were passed
jpiet>          
```

**Comment by ddutt** [comment]
Workaround is to use the query-str option to summarize, for example:
```
route summarize query-str='prefixlen <= 16' namespace=nxos
```

**Comment by ddutt** [comment]
I'll leave it with the workaround for now. It can be reopened if users request it.
