### ISSUE TITLE
Issue while launching suzieq on Ubuntu as standalone CLI

### ISSUE THREAD

**Issue by gadrenayan** [netenglabs/suzieq#119]
Hi,

I was trying to launch suzieq-cli as a stand alone application (i.e. without launching the docker image).
I am facing issues while loading the different commands listed in the sqcmds directory.

I had put some prints to debug the issue but after a certain point I have no clue to proceed.

root@ngadre-Inspiron-3542:~/suzieq# ./suzieq/cli/suzieq-cli
['AddressCmd', 'BgpCmd', 'MlagCmd', 'RouteCmd', 'InterfaceCmd', 'LldpCmd', 'SqPollerCmd', 'ArpndCmd', 'TableCmd', 'MacCmd', 'EvpnVniCmd', 'OspfCmd', 'VlanCmd', 'DeviceCmd', 'PathCmd']
<module 'suzieq.cli.sqcmds.AddressCmd' from '/root/suzieq/suzieq/cli/sqcmds/AddressCmd.py'>
Command {'name': 'address', 'help': 'Act on address data', 'aliases': [], 'exclusive_arguments': None}
super True ---> indicates its a super command
----> Then the attribute list obtained in inspect_object():
['__annotations__', '__arguments_decorator_specs', '__class__', '__command', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_assert_gen_output', '_gen_output', '_init_summarize', '_post_summarize', 'analyze', 'aver', 'cfg', 'schemas', 'show', 'summarize', 'top', 'unique']
#This is a nested call for inspect_object: 
Obj <function SqCommand.analyze at 0x7ff1f30e0ea0>
Command None --> **This is the issue !!**
Metadata FunctionInspection(arguments=OrderedDict(), command=None, subcommands={}) command None
Traceback (most recent call last):
  File "./suzieq/cli/suzieq-cli", line 10, in <module>
    options=Options(persistent_history=True))
  File "/usr/local/lib/python3.6/dist-packages/nubia/internal/nubia.py", line 137, in __init__
    for cmd in self._plugin.get_commands():
  File "/root/suzieq/suzieq/cli/sq_nubia_plugin.py", line 45, in get_commands
    print(AutoCommand(getattr(globals()[x], x)));
  File "/usr/local/lib/python3.6/dist-packages/nubia/internal/cmdbase.py", line 145, in __init__
    self._obj_metadata = inspect_object(fn);
  File "/usr/local/lib/python3.6/dist-packages/nubia/internal/typing/__init__.py", line 347, in inspect_object
    if not metadata.command.help:
AttributeError: 'NoneType' object has no attribute 'help'

Is this a bug, or is there something missing as part of executing the cli.

**Comment by jopietsch** [comment]
This is a problem in the nubia package, which is a dependency of Suzieq. In the requirements.txt it should be pointing to Dinesh's fork of nubia with the bug fix. 
How did you install all the Suzieq dependencies?
Also, which version of python are you using?

**Comment by gadrenayan** [comment]
Hi,

I am using python3.7, on Ubuntu 18.04. 
I installed dependencies using "pipenv install", however some packages were still not installed so I installed manually using "pip3 install pyarrow" etc.

I will switch to ddutt nubia fork and check using that.

Thanks

**Comment by ddutt** [comment]
Any updates whether switching to the nubia fork helped @gadrenayan ?

**Comment by gadrenayan** [comment]
Hi,
Yes, I can launch the CLI with the ddutt nubia fork.

Thanks.
