### ISSUE TITLE
NXOS and JUNOS don't have vlan info

### ISSUE THREAD

**Issue by jopietsch** [netenglabs/suzieq#154]
**Describe the bug**
cumulus does vlans unlike everybody else and we modeled it after cumulus. Need to change the vlan model to be able to accommodate more platforms

**Comment by ddutt** [comment]
Fixed in 0.6 release via commits 47e8ec7e3bc7d8e2fb8e05b865b8e8c79286bf8d and 94f7193eb2fb04691702307fbccd7b8fe3589afa
