### ISSUE TITLE
arpnd summarize should break out v4 and v6 addresses

### ISSUE THREAD

**Issue by jopietsch** [netenglabs/suzieq#162]
**Is your feature request related to a problem? Please describe.**
I don't know if we need this for this release, but it is a missing v6 feature

this is what it looks like now
```
jpiet> arpnd summarize
                  dual-bgp
deviceCnt               14
arpNdEntriesCnt        120
macaddrCnt             120
oifCnt                 120
uniqueOifCnt            17
remoteEntriesCnt         0
staticEntriesCnt        46
failedEntryCnt           0
jpiet> 
```
needs to show v6 entry count and v4 entry count, possibly even LLA vs global v6

**Comment by ddutt** [comment]
Closed in 0.16.0 alpha release
