### ISSUE TITLE
vxlan-evpn add asserts for BUM traffic based on multicast underlay

### ISSUE THREAD

**Issue by anubisg1** [netenglabs/suzieq#181]
as per title, we need an assert where we check the multicast group used for BUM traffic

**Comment by ddutt** [comment]
Closed with commit 0051069353217574406366731d9fbd7ba3b8a57a

**Comment by ddutt** [comment]
Closed with commit 0051069353217574406366731d9fbd7ba3b8a57a.

We added support for ensuring that in a given namespace, all VTEPs use the same multicast group for a VNI
