### ISSUE TITLE
sq-poller doesn't respect the maximum 4 active connection per host rule

### ISSUE THREAD

**Issue by anubisg1** [netenglabs/suzieq#191]
as visible here, the sq-poller can generate even 9 connections or more 

![image](https://user-images.githubusercontent.com/4518931/85929284-daef6400-b8b3-11ea-81e4-71dc0bbffed5.png)

**Comment by anubisg1** [comment]
i was able to reach 14 active connections to a single host. I'm assuming it will try to get 1 connection per service

![image](https://user-images.githubusercontent.com/4518931/85929342-31f53900-b8b4-11ea-8333-7d4f12a762da.png)

**Comment by anubisg1** [comment]
before shutting down the poller, i reached 20 active sessions :-/

**Comment by jopietsch** [comment]
I cannot reproduce this. can you set the logging-level to INFO and give us the log data? 

I don't think we have an editor, so one way to do that is:
```
root@1e07a7dd1361:/suzieq# cat <<'EOF' >/root/.suzieq/suzieq-cfg.yml
data-directory: /suzieq/parquet
service-directory: /suzieq/config
schema-directory: /suzieq/config/schema
temp-directory: /tmp/parquet
logging-level: INFO
EOF
```

then delete your previous /tmp/sq-poller.log

then start sq-poller again. run it for 30 seconds, and send us /tmp/sq-poller.log

**Comment by ddutt** [comment]
Even though we don't have an editor by default, its just a Debian buster container and so you can apt install your favorite editor

**Comment by anubisg1** [comment]
30 seconds didn't provide much information, as you can see that new sessions get formed over time and old ones are not closed.

i had to run it for a few minutes to get at least 5 connections (they just keep on increasing)... 
[sq-poller.log](https://github.com/netenglabs/suzieq/files/4850803/sq-poller.log)

**Comment by jopietsch** [comment]
fixed
