### ISSUE TITLE
add the ability to exclude items in "admin_down" state from asserts

### ISSUE THREAD

**Issue by anubisg1** [netenglabs/suzieq#192]
i might have an interface, a BGP neighbor or OSPF neighbor for example which are admin down (shut down by config).
While sometimes this needs to be detected, because an engineer might have forgotten about it, other times, those objects might be down by design.

when running asserts, suzieq should allow the user to ignore admin_down objects, for example by using --exclude=shutdown 

ospf assert --exclude=shutdown (or any other meaningful keyword)

**Comment by ddutt** [comment]
We ignore interfaces that are adminDown automatically now
