### ISSUE TITLE
Mlag systemId and domainId are the same thing

### ISSUE THREAD

**Issue by anubisg1** [netenglabs/suzieq#219]
as per title, the two objects are the same thing and one of them should be deleted while the other kept

**Comment by ddutt** [comment]
I use the systemID to store the system MAC in case of NXOS and EOS. DomainID which is used by NXOS and EOS is blank for Cumulus. Therefore, having both is OK.

**Comment by anubisg1** [comment]
So, what do those things represent? That part isn't clear.

If are the same thing, should we abstract and keep one? 
If they aren't the same, what's the difference between the two?

**Comment by ddutt** [comment]
So, AFAIK, NXOS and EOS have two separate things: domainID is user-specified and systemMAC is determined by the NOS itself(?). Cumulus has only thing, the systemMAC which it calls systemID. Thats why we need both systemID (user-specified in Cumulus, system determined in NXOS/EOS) and domainID(user-specified in NXOS/EOS, unused in Cumulus).

Does that make better sense why we need both?

**Comment by anubisg1** [comment]
Ok I understand. Btw, on nx-os the system Mac (or virtual Mac address used by the vPC cluster) is derived by the vPC domain ID. It's a static Mac address with the last 2 digits being the vPC domain
