### ISSUE TITLE
CEST timezone date crashes sq-poller

### ISSUE THREAD

**Issue by fdebonneval** [netenglabs/suzieq#221]
**Describe the bug**
Running sq-poller against a Juniper router in "Europe/Paris" timezone breaks datetime.strptime()

**To Reproduce**
1. Check router's timezone configuration `show configuration system time-zone`
2. Go to router and get system uptime with `show system uptime` from the cli
3. Get the curent time value, for example '2020-07-15 18:28:52 CEST'
4. give it to `datetime.strptime()` and watch the error
```
>>> datetime.strptime('2019-07-09 10:46:39 PST', '%Y-%m-%d %H:%M:%S %Z')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/_strptime.py", line 577, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/local/lib/python3.7/_strptime.py", line 359, in _strptime
    (data_string, format))
ValueError: time data '2019-07-09 10:46:39 CEST' does not match format '%Y-%m-%d %H:%M:%S %Z'
```

**Expected behavior**
CEST should be a valid TimeZone.

**Additional context**
It seems that datetime library allows only "GMT", "UTC", "-500", "-5:00", "EDT", "US/Eastern", "America/New York" formats.

**Comment by ddutt** [comment]
Sadly this is no longer easily supportable in Python it seems (as per https://stackoverflow.com/questions/241789/parse-datetime-with-time-zone-of-form-pst-cest-utc-etc) due to valid reasons. If only NOS vendors stopped using antiquated ways of being in the world. 

Am investigating how to solve your problem. It needs to be addressed. Thanks for reporting the issue.

**Comment by ddutt** [comment]
@fdebonneval : If you need an image to try this fix, you can try the docker nightly image we build: ddutt/suzieq:prerc.

**Comment by fdebonneval** [comment]
Hi Dinesh,

Thanks for the very quick fix.
I do not know if the fix broke something, but now sq-poller silently crash almost immediatly.
How can I help, it does not seem to have a verbose output for sq-poller.

```
root@4f68d9e3963b:/suzieq# time sq-poller -D inventory -n ubone-fr; echo $?

real	0m0.706s
user	0m0.641s
sys	0m0.138s
1
```

**Comment by ddutt** [comment]
Hi @fdebonneval ,

That's disappointing. Do you mind joining the Slack channel? The link to join without having to email either Justin or I is: https://join.slack.com/t/netenglabs/shared_invite/zt-g64xa6lc-SeP2OAj~3uLbgOWJniLslA. We can debug this far easier over Slack is my prediction. 

To your q. I presume the inventory file is not in the Ansible inventory format(you're using -D, not -i) ? Can you look at /tmp/sq-poller.log. That usually has something useful if things end badly.

**Comment by fdebonneval** [comment]
Tested with the last prerc image and patch is ok;
Thanks Dinesh
