### ISSUE TITLE
Slow response on Junos for command # show arp | display json

### ISSUE THREAD

**Issue by fdebonneval** [netenglabs/suzieq#225]
**Describe the bug**
On Junos (MX, EX, QFX, SRX), command `show arp | display json` take very long time to respond. It seems that the system is trying to resolve PTR on IP addresses.

**To Reproduce**
1. Go to any Junos device
2. Type `show arp | display json` and measure time until it completes
3. IF PTR does not exists, commands takes a long time to respond

**Expected behavior**
Return from the command should be almost instant

**Additional context**
I'd recommand to use `show arp no-resolve | display json` instead

**Comment by ddutt** [comment]
Fixed with commit 0284487031ba88b54fc67caf4459db2796dff2d5
