### ISSUE TITLE
ArcOS integration 

### ISSUE THREAD

**Issue by dt-arrcus** [netenglabs/suzieq#244]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would like to begin working on integrating ArcOS into this tool

**Additional context**
Are there are guides about the steps needed to add additional OS support?

**Comment by jopietsch** [comment]
https://github.com/netenglabs/suzieq/blob/master/docs/developer/adding-a-new-nos.md is what we have, it should get you started. The best way is to then join our slack and in the suzieq-dev channel ask questions. https://join.slack.com/t/dd-friends/shared_invite/zt-ha5c8qow-cIf4XqFB7XgDTGR6x4P9Og

**Comment by dt-arrcus** [comment]
@jopietsch Thanks for the link, that will definitely get me started.

@anubisg1 https://www.arrcus.com/ will give you some more info.  I am happy to answer any questions if you want to ping me offiline.
