### ISSUE TITLE
Error when launching 'sq-poller' using native YAML hosts file

### ISSUE THREAD

**Issue by jag-s2** [netenglabs/suzieq#255]
**Describe the bug**
When attempting to launch the 'sq-poller' using a native inventory file format (using Juniper vMX devices), the following error message is seen:
```
AttributeError: 'list' object has no attribute 'keys'
```
NOTE: This error was not seen in an earlier version of Suzieq.

**To Reproduce**
1. Setup access to Juniper vMX using SSH keys by creating a local SSH Key (`ssh-keygen -t rsa`) and configuring the appropriate user on the vMX.

2. Verify that the SSH access to the device works from the Suzieq container: (`ssh -i <PATH_TO_PRIVATE_KEY> <USERNAME>@<DEVICE_IP>`)

3. Create the Suzieq native format Devices YAML file (sample used shown below):
```
root@b14b4eecb1f6:/suzieq# more junos.yml 
- namespace: junos
  hosts:
    - url: ssh://jag@192.168.249.111 keyfile=/home/jag/.ssh/id_rsa_juniper
```

4. Error seen shown below:
```
root@b14b4eecb1f6:/suzieq# sq-poller -D /suzieq/junos.yml
Traceback (most recent call last):
  File "/root/.local/lib/python3.7/site-packages/suzieq/poller/sq-poller", line 317, in <module>
    asyncio.run(start_poller(userargs, cfg))
  File "/usr/local/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/root/.local/lib/python3.7/site-packages/suzieq/poller/sq-poller", line 149, in start_poller
    nodes, svcs = await asyncio.gather(*tasks)
  File "/root/.local/lib/python3.7/site-packages/suzieq/poller/nodes/node.py", line 96, in init_hosts
    hostsconf = get_hostsdata_from_hostsfile(inventory)
  File "/root/.local/lib/python3.7/site-packages/suzieq/poller/nodes/node.py", line 63, in get_hostsdata_from_hostsfile
    if any(x not in hostsconf.keys() for x in ['namespace', 'hosts']):
  File "/root/.local/lib/python3.7/site-packages/suzieq/poller/nodes/node.py", line 63, in <genexpr>
    if any(x not in hostsconf.keys() for x in ['namespace', 'hosts']):
AttributeError: 'list' object has no attribute 'keys'
```

**Additional context**
As a test, in `/suzieq/poller/nodes/node.py`, I added a debug statement to print the value of 'hostsconf' after line 45 (https://github.com/netenglabs/suzieq/blob/master/suzieq/poller/nodes/node.py#L45), and its value is:
```
[{'namespace': 'junos', 'hosts': [{'url': 'ssh://jag@192.168.249.111 keyfile=/home/jag/.ssh/id_rsa_juniper'}]}]
```
I am able to bypass this error if I change line 62 (https://github.com/netenglabs/suzieq/blob/master/suzieq/poller/nodes/node.py#L62) and line 67 (https://github.com/netenglabs/suzieq/blob/master/suzieq/poller/nodes/node.py#L67) in `/suzieq/poller/nodes/node.py` to use `hostsconf[0]` instead of `hostsconf`.

**Comment by ddutt** [comment]
Fixed with 0809beb6c49c9dcefe0c9dfa20eba2ff0b5ad63a
