### ISSUE TITLE
Support Juniper EX series

### ISSUE THREAD

**Issue by dsinn23** [netenglabs/suzieq#273]
It would be useful to add support for the Juniper EX platforms as they are a commonly used L2 platform in Juniper deployments.

**Comment by anubisg1** [comment]
In the case of vxlan-evpn deployment (see Juniper ex4300-mp) the same driver as the QFX work.

I can provide help with ex4300-mp supporting evpn and 2300 (i believe) which does not.

**Comment by anubisg1** [comment]
i made a PR adding support. 

@ddutt  can you add me as owner ?

**Comment by anubisg1** [comment]
@dsinn23  can you please try the latest code? support to EX switches was added

**Comment by ddutt** [comment]
Fixed with commit 69d5ca1848976c112892da0a7566cfd1d4b5d16c. 
Works with version 20.x. Need to independently verify if it works with earlier versions.
