### ISSUE TITLE
Regex support

### ISSUE THREAD

**Issue by mojana** [netenglabs/suzieq#278]
**Is your feature request related to a problem? Please describe.**
It isn't possible to use regex to do smart filtering on the queries. Regex would be very powerful to gather more granular output.

**Describe the solution you'd like**
Use regex to get more control on output of queries.

**Additional context**
Example: interface show ifname=port-channel1*
This example would list all subinterfaces belonging to port-channel1

**Comment by ddutt** [comment]
Support for hostname and namespace regex has been added. The other ones are not done yet. If this is sufficient for now, I'll close this issue for now and reopen for specific values.

The way to add regex is to start the value with ~. Python regexps are the only ones accepted. So, if all spine switches start with the name spine, the regex for selecting all spines is ~spine.*

The commit that adds this support is e3968e17e83950e0fe7806c5a22faee88305efff.

@mojana please let me know if we can close this.
