### ISSUE TITLE
VLAN name support

### ISSUE THREAD

**Issue by mojana** [netenglabs/suzieq#279]
**Is your feature request related to a problem? Please describe.**
The vlan output is really powerful, but having also the name of the vlan instead of only the vlan-number, would be more powerful as vlan names tell a lot of information. In my network, vlan names have a specific naming-convention and give insight in some basic information, like in which DC is de vlan residing? For example: Anywhere or only local. It also has a regex friendly structure.

**Describe the solution you'd like**
Gather VLAN names from system and present it when quering information when now only vlan-numbers are presented.

**Additional context**
n/a

**Comment by ddutt** [comment]
Fixed via commit dbcbac645670167027e0a2b65b91d44eded3ad0d, 6241578fa8ce295e10e00962eba4aca2875ba0a4
