### ISSUE TITLE
Password encryption mechanism

### ISSUE THREAD

**Issue by rishabhpanickar** [netenglabs/suzieq#287]
The passwords in the YAML file for hosts are in cleartext currently. This will cause a security issue. 

```
- namespace: test
  hosts:
    - url: https://test:test@10.1.1.1 devtype=eos
```

It would be helpful if we have a mechanism to store the passwords in an encrypted manner. 

Solution:
Use a gpg encrypted file to store the password and provide the password to decrypt via a prompt at the poller.

**Comment by ddutt** [comment]
We agreed, @rishabhpanickar and I, that prompting for a password on sq-poller startup was sufficient to satisfy the requirement to not have passwords stored in the clear in an inventory file. 

This feature has been implemented via the --ask-pass option passed to the poller via commit 634b61f93450ae8ef16899056517d3b4eacf1fc7
