### ISSUE TITLE
Disable pagination

### ISSUE THREAD

**Issue by Ji-Shao** [netenglabs/suzieq#314]
**Describe the bug**
Error logs showed time-out for command "show route" as the router we tested had a fair large routing table.
While command "show version" ran succesfully.
Maybe we need to disable pagination.

**Comment by ddutt** [comment]
Thank you @Ji-Shao for engaging, and filing a ticket. We'll need more info to figure out what's going on.

Could you please tell us what device/OS are you pulling the routes from? What version of the OS on the router(like JunOS 19.4R1 etc.)? The default period is 15s and so the command times out in 10s. Maybe you can try increasing the period? In the file config/routes.yml, please add the line:
`period: 90`
after the first line `service: routes` and try to see if that fixes the timeout problem. If not, please try to increase it to 120s. 

Dinesh

**Comment by Ji-Shao** [comment]
Hi Dinesh,

Thank you for your prompt response.

DUT info:
a. Juniper MX104
Junos Version: 16.1R4.7
Both "show route | dispaly json" and "show interface | display json" stopped responding under junos CLI.
Mostly it was a bug in Junos. Both "show route | display json | no-more" and "show route | display json | no-more" work fine under junos CLI

b. Juniper qfx10002-36Q
Junos Version: 18.4R2-S5.4
Both "show route | display json | no-more" and "show route | display json | no-more" work fine under junos CLI.

We added "| no-more" to the end of every junos command and increase period to 300 for routes.yml and interfaces.yml files.

Another issue:
"show evpn ip-prefix-database" is not valid command under Junos MX.  sp-poller.log shown "syntax error" when we polled Junos MX104.

May I make some suggestions:
a. Can we try to use xml?  for example, "show route | display xml | no-more".  It seems to me that it took less time compared with json output.
    In our case, "show route | display json" output over 75,000 lines. In the meantime, "show route | display xml" gave us 20,629.
b. Can we disable pagination before issue any commands? for example, for junos, we could issue "set cli screen-length 0" first.

Regards

Ji Shao
________________________________

**Comment by ddutt** [comment]
Hi @Ji-Shao,

Thanks for the feedback. 

I'll add "no-more" to the Junos commands, as per your suggestion. It should be there in the next release. Meanwhile, can you proceed with the change just local to you?

On the XML issue. I'm surprised that the Junos XML output is smaller than the JSON output because XML is so much more verbose compared to XML. But you're right. Parsing XML just for Junos is a pain I'd like to avoid if possible. Can we table that separately? Can you please file a separate bug about it. We'll see what we can do, though I don't promise a quick support for that.

So, is everything working OK with the addition of '| no-more' and increased timeout to 300s? Can you reduce it to 120s and see if it works fine?

Dinesh

**Comment by Ji-Shao** [comment]
After reducing it to 120, it stopped working.

2021-02-03 01:16:46,802 - suzieq.poller.services.service - ERROR - Received non-JSON output where JSON was expected for show evpn ip-prefix-database | display json | no-more on node mx104,
error: syntax error, expecting <command>: ip-prefix-database


2021-02-03 08:56:28,813 - suzieq.poller.nodes.node - ERROR - Unable to connect to mx104 show route | display json | no-more due to timeout

2021-02-03 09:00:23,817 - suzieq.poller.nodes.node - ERROR - Unable to connect to mx104 show route | display json | no-more due to timeout

**Comment by ddutt** [comment]
Thanks for that @Ji-Shao. Wow, the box is really slow. I'd be inclined to try 180 secs, before giving up and switching back to 300.

**Comment by Ji-Shao** [comment]
180 seconds works.

**Comment by ddutt** [comment]
Fixed with commit a992a766a6b5d3513eb9aaf5a7a8574303a8acf4
