### ISSUE TITLE
Logging for Arista devices to suggest user to use https and not ssh

### ISSUE THREAD

**Issue by mechkhans** [netenglabs/suzieq#327]
**Is your feature request related to a problem? Please describe.**

The inventory file requires the url for arista to use https instead of ssh, this is not very clear for newer users who are coming aboard to suzieq.

```
- namespace: eos
  hosts:
    - url: https://vagrant@192.168.123.252 devtype=eos
```

**Describe the solution you'd like**

Please include a suggestion in the sq-poller.log file to use https and not ssh if devtype=eos is detected in inventory or some other help for users to self-correct the inventory file.

**Comment by ddutt** [comment]
This has been fixed. You can use SSH or REST now, though REST is recommended. Fixed via commit 0ad2a7aaad4c87a6476f444808f7d3e54d5e3344 and 8f80d8f4e86e333375471846092f8efd28bec9f0
