### ISSUE TITLE
engines has data in arpnd that we are dropping based on only macaddr difference

### ISSUE THREAD

**Issue by jopietsch** [netenglabs/suzieq#33]
the data I'm using is in tests/data/basic_dual_bgp, and looking at arpnd table.
the data saved in the csv was produced with view='', and it has 75 lines. When I run the query with view='latest', then I only get 74 lines. The duplicate lines that are merged are:
```
(Pdb) df_two[54:56]
   datacenter   hostname   ipAddress    oif            macaddr  state  offload               timestamp
54   dual-bgp  server102  172.16.2.1  bond0  52:54:00:9e:4c:92  stale    False 2020-01-24 22:28:45.696
55   dual-bgp  server102  172.16.2.1  bond0  52:54:00:c5:40:6d  stale    False 2020-01-24 22:28:45.696
```
the only difference is in the macaddr, but when you do a view='latest', then you drop duplicates by key_fields, and macaddr is not a keyfield so that this gets dropped. they all have the same timestamp.
Is this what we want?

**Comment by ddutt** [comment]
Yes, it shouldn't happen that we have the same IP addr with different MAC at the same time on the same host. This was most likely due to a bug in the very early days of the code (this is Feb 20, 2020 :)
