### ISSUE TITLE
Poller fails silently if there is bad inventory

### ISSUE THREAD

**Issue by benner** [netenglabs/suzieq#355]
**Describe the bug**
If inventory not valid YAML, `hostsconf = yaml.safe_load(data)` will be `str` type and `hostsconf.keys()` fails.
Responsible code lines:
https://github.com/netenglabs/suzieq/blob/master/suzieq/poller/nodes/node.py#L52-L53

**To Reproduce**
1. `sq-poller -D /etc/passwd`

**Attach**
```
root@00bc1be8c6ec:/suzieq# cat /tmp/sq-poller.log 
2021-03-30 12:27:09,575 - suzieq.poller - WARNING - log level WARNING
```

 **Expected behavior**
I expect at least some error massage that configuration is not valid `YAML` file/not parsed as list or similar

**Additional context**
N/A

**Comment by ddutt** [comment]
Thanks for filing a report. Its surprising that with /etc/passwd you got no exception or such. What version of suzieq?

**Comment by ddutt** [comment]
Never mind. I see that you reported an exception. Fixing it in upcoming release

**Comment by benner** [comment]
Also it is part of my "why it's not working". Actual problem I met is 

```
- namespace: some
  hosts:
    - url ssh://127.0.0.:2221 username=root devtype=cumulus keyfile=/root/.ssh/id_ed25519
```

No `:` after `url`. Exception:

```
AttributeError: 'str' object has no attribute 'get'
```
Code line: https://github.com/netenglabs/suzieq/blob/master/suzieq/poller/nodes/node.py#L143

**Comment by ddutt** [comment]
Fixed the first one already. Fixing the second now.
