### ISSUE TITLE
Configurable timeouts

### ISSUE THREAD

**Issue by benner** [netenglabs/suzieq#359]
**Is your feature request related to a problem? Please describe.**

After played with few Cumulus boxes I added more from remote locations and started to get timeouts. Searched around and it seems these are hardcoded (https://github.com/netenglabs/suzieq/blob/master/suzieq/poller/nodes/node.py#L240-L241). To move forward I manually edited node.py.

**Describe the solution you'd like**
It would be great if these settings can be configurable in inventory or as command line arguments.

**Additional context**
N/A

**Comment by ddutt** [comment]
@benner I'll add the fix to the next release most likely, I presume you can proceed for now? Are you held up?

**Comment by benner** [comment]
Yes, I can proceed
