### ISSUE TITLE
Table widths of output

### ISSUE THREAD

**Issue by mojana** [netenglabs/suzieq#364]
**Is your feature request related to a problem? Please describe.**
SuzieQ uses fixed table widths, which trims some output when a field as more information than  one entry.

**Describe the solution you'd like**
Adjustable table widths or auto-sizing, but if output contains a lot of information, like interfaces used with a vlan, a drill down option per LINE would be a better solution.

**Additional context**
Example of timming:
1
  namespace          hostname          vlanName   state                                         interfaces  vlan                        timestamp
0    DC-MST  TESTSW207  TEST-KLE5_BACKEND  active  [port-channel1, port-channel3026, Ethernet1/15...  2146 2021-04-16 13:26:11.774000+00:00

**Comment by ddutt** [comment]
This is fixed with commit 3daf17f14253627b555aecd39504acf4de4dd146

Use set col_width= at the CLI prompt
