### ISSUE TITLE
Add support for dynamic inventory

### ISSUE THREAD

**Issue by rasanentimo** [netenglabs/suzieq#369]
### Problem

Currently Suzieq supports only inventory as static files in either default Suzieq or Ansible inventory format. However, the inventory might be in other formats or stored to some tools like Netbox. Dynamic inventory would make it easier to work in constantly changing environment, convert between different inventory formats and also scale up Suzieq pollers.

### Proposed solution
Suzieq could have an option to pass the inventory information from a script in a similar way as with Ansible dynamic inventory. 

- https://docs.ansible.com/ansible/latest/user_guide/intro_dynamic_inventory.html 
- https://docs.ansible.com/ansible/latest/dev_guide/developing_inventory.html

For example Netbox dynamic inventory script could read certain env variables or arguments, use those for the filtering criteria and pull the data over the Netbox rest api.

**Comment by ryanmerolle** [comment]
Pulling device inventory via Ansible plugin or just an api call to netbox would be great!

**Comment by ryanmerolle** [comment]
I think dynamic inventory or even just an API endpoint for adding devices to the device inventory.

**Comment by ddutt** [comment]
Support added to 0.16.0 alpha
