### ISSUE TITLE
FR: Add option to write pandas data to Postgres

### ISSUE THREAD

**Issue by ryanmerolle** [netenglabs/suzieq#376]
**Is your feature request related to a problem? Please describe.**
It would be useful to add a option to write pandas data to a postgres database.

**Describe the solution you'd like**

1. Provide the additional setting(s) to enable postgres integration.
2. Define the schema file and a process for creating the database.
3. Provide database migrations from version to version to handle new or updated data models that would impact an existing table.

**Additional context**

1. Postgres support inet datatypes & json datatypes which should lend itself to the data being gathered from network devices.
2. Python & Pandas lends it self well to pointing to a SQL backend of data storage.
3. SQL provides operators and additional way in which they could leverage the suzieQ gathered data.  I know plenty of infrastructure and development stakeholders in my organization that may not be well versed with interacting with SuzieQ currently, but would find huge value and lowered barrier to entry if the data was in SQL.

**Comment by ddutt** [comment]
For the purposes of your use case, any reason you cannot use something like Apache Drill? You can get started today with no change from Suzieq :)

**Comment by ryanmerolle** [comment]
Well,first of all, that is a totally valid response.  A maintainer does not need to add complexity to there project just for a user myself.  

The down side for is me I'll have to take my previous sql queries,existing Postgres tables, and adapt it to leverage drill.  It is really just about quickly plugging into my existing ops toolset and general getting started with Susie-Q while minimizing the learning curve.

I figured it was worth asking since from, my quick intro to pandas it seemed like it could be done.

**Comment by ddutt** [comment]
Everything is do'able, its a question of time and priority and most importantly testing. Yes, instead of using pyarrow to write to Parquet, I could do pandas.to_sql, and pandas.read_sql. Yes, that is certainly do'able. It requires writing a new backend under suzieq/db. Patches, and tests welcome :)

**Comment by ddutt** [comment]
Its essentially supporting the API listed in suzieq/db/base_db.py. Adding postgres support maybe trivial enough given pandas support. I can help you if you like.

**Comment by ddutt** [comment]
@ryanmerolle Please let me know if you'd like to leave this issue open or close it.
