### ISSUE TITLE
More polished/cohesive docker-compose packaging

### ISSUE THREAD

**Issue by ryanmerolle** [netenglabs/suzieq#382]
**Is your feature request related to a problem? Please describe.**
The current docker-compose file and fastapi setting for the rest server process need some attention and polish.

**Describe the solution you'd like**

- Expand on current docker-compose services to create a container for each suzieq component.
- Introduce a cohesive HTTPS solution beyond the included/seperate fastapi or streamlit HTTPS
- Update fastapi url structure to more easily allow reverse proxy forwarding for the cohesive HTTPS solution.
- Update documents accordingly.

**Additional context**
This should be updated in the same directory.

**Comment by ddutt** [comment]
Please add the docker compose file in the build dir

**Comment by ryanmerolle** [comment]
It would be confusing with the fact we have the sample directory also.  Would you liked that deleted?

**Comment by ddutt** [comment]
I forgot about that, thanks for catching that. No please put it there. If this file supersedes the existing one, then get rid of the existing one.
