### ISSUE TITLE
Duplicate Records on Poller Restart

### ISSUE THREAD

**Issue by rickdonato** [netenglabs/suzieq#388]
**Describe the bug**
When the poller is restarted the tables show duplicate entries.

**To Reproduce**
1. restart poller. 
2. look at the table with a `view=all`

**Attach**
N/A

 **Expected behavior**
The duplicates are removed on startup so only differences are seen within the table.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by ddutt** [comment]
Fixed in 0.17.1
