### ISSUE TITLE
CLI/GUI/Python via REST Support

### ISSUE THREAD

**Issue by rickdonato** [netenglabs/suzieq#390]
**Describe the bug**
Currently the CLI GUI and Python need direct access to the parquet files. This issues is around providing support within the CLI/GUI and Python for it to use REST as a southbound API. This would then provide more flexibility into use cases such as CI etc.

**To Reproduce**
N/A

**Attach**
N/A

 **Expected behavior**
N/A

**Screenshots**
N/A

**Additional context**
N/A

**Comment by JulioPDX** [comment]
Hey @rickdonato I think we are facing a similar issue to integrate suzieq with CI

**Comment by ddutt** [comment]
CLI/Python support for this introduced via 0.16.0 alpha release

**Comment by ddutt** [comment]
Fixed via various commits. Version 0.17.1 should have it all.
