### ISSUE TITLE
Add support to "endpoint tracker"

### ISSUE THREAD

**Issue by anubisg1** [netenglabs/suzieq#393]
**Is your feature request related to a problem? Please describe.**
Allow to search an endpoint via mac or ip address in order to obtain information about it across all tables.

**Describe the solution you'd like**
I want to be able to search an endpoint by looking for either it's mac or ip address.
SuzieQ should perform a lookup across multiple tables and return the following data in a table:

- MAC address + IP address (lookup into arpnd table)
- Physical location of the mac address ( mac table, "local only" , making sure to exclude "peer-link" results ). When the host is behind a port-channel, the interfaces table needs to be looked at so the physical interface is eventually returned 
- Vlan(s) where the mac address exist ( mac table + vlan table) 

**Additional context**
A next step improvement would be to allow to search for all endpoints in a vlan 
I'd like to have the same as the above, but for all known hosts in a specific vlan.

**Comment by ddutt** [comment]
Added a command "network find" to support this feature, and provide the outputs requested in this ticket. Fixed with commit: c780e3ae5b017c96e9c7b6a4cd5d71ea53032eac
