### ISSUE TITLE
Rest API - add "get namespaces" 

### ISSUE THREAD

**Issue by anubisg1** [netenglabs/suzieq#398]
When using Rest API, an assumption needs to be made that the developer doesn't know "a priori" what configuration is applied to suzieq , as it's likely that a generic application is being written.

specifically it's impossible today to know what namespaces exist without querying some table first, for everything, then find and exclude duplicates.

a "get namespaces" API should be provided, that only returns the list of available/configured namespaces .

other similar APIs might be needed, but i can't think of one at this moment

**Comment by ddutt** [comment]
This has been fixed with the network virtual table support, starting with commit 289cffa6217ea7339be3b3bff92da6ab55ff9993
