### ISSUE TITLE
bgp show - Junos VRF info missing

### ISSUE THREAD

**Issue by gpipito** [netenglabs/suzieq#404]
**Describe the bug**
suzieq-cli not reporting Junos vrf information in bgp show command

**To Reproduce**
1. Launch suzieq-cli
2. run "bgp show"
3. vrf column only reports default value

**Attach**
N/A

 **Expected behavior**
the correct vrf value should be reported in the vrf column

**Screenshots**
Problem:
![image](https://user-images.githubusercontent.com/50398686/129896783-ae7a8ea4-81b1-4d30-9cdc-4cc5c3f43f6b.png)

After fix:
![image](https://user-images.githubusercontent.com/50398686/129896854-67ab04a4-29c0-4723-9ea0-3c83ebf64f1e.png)

**Additional context**
The issue can be fixed replacing every occurrence of the following line in file /usr/local/lib/python3.7/site-packages/suzieq/config/bgp.yml

replace 

"vrf: vrf?|default",

with

"bgp-rib/[*]/name/[0]/data: vrf",

Thanks @anubisg1 for the fix

**Comment by anubisg1** [comment]
@ddutt  this might need more work on your end to fix properly. but you get the point of the fix i guess :) right ? :)
