### ISSUE TITLE
Add IOS to Supported 

### ISSUE THREAD

**Issue by Neelajacques** [netenglabs/suzieq#406]
**Describe the bug**
List of supported OS is not up to date here: https://suzieq.readthedocs.io/en/latest/poller/#gathering-data

(missing IOS) 

Also, let's make alphabetical, consistent across sources... and do Vendor OS as a format 

From: "Currently Suzieq supports polling Cumulus Linux, Arista, Nexus, and Juniper and SONIC devices, as well as native Linux devices such as servers. Suzieq can easily support other device types, and we have third-party contributors working on other NOSes. Please let us know if you're interested in Suzieq supporting other NOSes."

Note extra And should also be removed

**Comment by aegiacometti** [comment]
@Neelajacques please check the PR #424, one of the commits is related to this issue. If you are OK please close this issue.
