### ISSUE TITLE
Add Palo Alto Networks panOS support

### ISSUE THREAD

**Issue by gpipito** [netenglabs/suzieq#408]
**Is your feature request related to a problem? Please describe.**
It would be good to add palo alto support to suzieq

**Additional context**
PanOS supports REST calls
https://docs.paloaltonetworks.com/pan-os/9-0/pan-os-panorama-api/get-started-with-the-pan-os-rest-api/pan-os-rest-api.html

**Comment by ddutt** [comment]
Fixed, available since version 0.16.0. Try the latest version please.
