### ISSUE TITLE
MLAG Support for Junos

### ISSUE THREAD

**Issue by Mierdin** [netenglabs/suzieq#410]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
I noticed in the [feature table](https://suzieq.readthedocs.io/en/latest/tables/) that there's no current support for MLAG on Junos. I'm interested in contributing support for this feature, but wanted to ask if there was any discussion on this previously that I don't know about, or any other specific reason it doesn't exist yet that I should know about before jumping in.

**Additional context**
N/A

**Comment by ddutt** [comment]
Hi Matt,

No discussions were made regarding this. I just didn't know how to support MLAG in Junos. Is it supported in vQFX?

Dinesh

**Comment by ddutt** [comment]
Thanks for offering to contribute, Matt.

**Comment by Mierdin** [comment]
Ack, thank you.

> Is it supported in vQFX?

Yes, it should be. [Here's](https://jncie.eu/mc-lag-on-vqfx-eve-ng/) a blog where someone managed to get it working.

For context, I was perusing the docs and noticed the Junos support in SuzieQ these days is really quite good! Just noticed the MLAG gap in the feature table so wanted to ask for a little history before I jumped into anything. If I have a chance to work on this I'll open a PR and link here.

**Comment by Mierdin** [comment]
Just a quick update - it's highly unlikely I'll have time to work on this in the near future, so I'll close this for now.
