### ISSUE TITLE
parser not matching OSPF External routes and default candidates

### ISSUE THREAD

**Issue by aegiacometti** [netenglabs/suzieq#416]
**Describe the bug**
Some routes are not being matched by the TextFSM template defined at file [iosxe_show_route.tfsm](https://github.com/netenglabs/suzieq/blob/master/suzieq/config/textfsm_templates/iosxe_show_route.tfsm), henced not being collected and showed with **suzieq-cli**.

**Examples:**
1.- OSPF "IA" routes
2.- candidate default routes

**Expected behavior**
Routes should appear in suzieq normally

**Additional context**
Running on GNS3 old IOS versions
3700 Software (C3725-ADVENTERPRISEK9-M), Version 12.4(15)T13, RELEASE SOFTWARE (fc3)

**To Reproduce**
Just execute the template [iosxe_show_route.tfsm](https://github.com/netenglabs/suzieq/blob/master/suzieq/config/textfsm_templates/iosxe_show_route.tfsm) with this file as input.
[example1.txt](https://github.com/netenglabs/suzieq/files/7124628/example1.txt)

You can use this simple script to do it
```
import textfsm
from tabulate import tabulate

template = sys.argv[1]
output_file = sys.argv[2]

with open(template) as f, open(output_file) as output:
    re_table = textfsm.TextFSM(f)
    header = re_table.header
    result = re_table.ParseText(output.read())
    print(result)
    print(tabulate(result, headers=header))
```

**Output example:**
```
vrf    protocol    prefix    preference    metric    nexthopIps    oifs                 statusChangeTimestamp    nexthopvrf
-----  ----------  --------  ------------  --------  ------------  -------------------  -----------------------  ------------
       O           1.0.1.0   110           41        ['3.3.0.2']   ['FastEthernet0/0']  00:01:07
       C           3.3.0.0                           []            ['FastEthernet0/0']
       O           3.0.0.0   110           40        ['3.3.0.2']   ['FastEthernet0/0']  00:01:07
       C           3.4.0.0                           []            ['FastEthernet0/1']
       O           20.0.0.0  110           41        ['3.3.0.2']   ['FastEthernet0/0']  00:01:09
       O           10.0.0.1  110           41        ['3.3.0.2']   ['FastEthernet0/0']  00:01:12
```

**Proposed solution:**
In the file [iosxe_show_route.tfsm](https://github.com/netenglabs/suzieq/blob/master/suzieq/config/textfsm_templates/iosxe_show_route.tfsm) replace the protocol value line
`Value protocol ([A-Zi]\*?|[A-Zio]\s+[A-Z][1-2]|i ia|i su|LC)`
with
`Value protocol ([A-Zi]\*?\s+|[A-Zio][\*\s][A-Z][1-2]|[A-Z][\*\s][A-Z][A-Z]|i ia|i su|LC)`

**Proposed solution output result:**
```
vrf    protocol    prefix     preference    metric    nexthopIps              oifs                                    statusChangeTimestamp    nexthopvrf
-----  ----------  ---------  ------------  --------  ----------------------  --------------------------------------  -----------------------  ------------
       O           1.0.1.0    110           41        ['3.3.0.2']             ['FastEthernet0/0']                     00:01:07
       C           3.3.0.0                            []                      ['FastEthernet0/0']
       O IA        3.2.0.0    110           20        ['3.3.0.2']             ['FastEthernet0/0']                     00:01:35
       O IA        3.1.0.0    110           30        ['3.3.0.2']             ['FastEthernet0/0']                     00:01:35
       O IA        3.1.1.0    110           21        ['3.3.0.2']             ['FastEthernet0/0']                     00:01:35
       O           3.0.0.0    110           40        ['3.3.0.2']             ['FastEthernet0/0']                     00:01:07
       O IA        3.4.2.0    110           30        ['3.4.0.2']             ['FastEthernet0/1']                     00:01:46
       O IA        3.4.1.0    110           20        ['3.4.0.2']             ['FastEthernet0/1']                     00:01:46
       C           3.4.0.0                            []                      ['FastEthernet0/1']
       O           20.0.0.0   110           41        ['3.3.0.2']             ['FastEthernet0/0']                     00:01:09
       O IA        5.0.0.0    110           21        ['3.3.0.2']             ['FastEthernet0/0']                     00:01:40
       O*E2        0.0.0.0/0  110           1         [**'3.3.0.2', '3.3.0.2']  ['FastEthernet0/0', 'FastEthernet0/0']  00:01:12
```

**EXTRAS**

Also **ADD** this line:
`^${protocol}\s+${prefix}\s+\[${preference}/${metric}\]\s+via\s+${nexthopIps}`
to match static default routes since they don't have the variable **statusChangeTimestamp** and **oifs** as per example in the same template file **iosxe_show_route.tfsm**.
`S*    0.0.0.0/0 [254/0] via 10.255.1.1`

And **MODIFY** this line:
`^[A-Zio]\s -> Continue.Record`
According to the example file, there is an error in the collection
```
       O IA        5.0.0.0    110           21        ['3.3.0.2']             ['FastEthernet0/0']                     00:01:40
       O*E2        0.0.0.0/0  110           1         [**'3.3.0.2', '3.3.0.2']  ['FastEthernet0/0', 'FastEthernet0/0']  00:01:12**
```
While it should be
```
       O IA        5.0.0.0     110           21        ['3.3.0.2']   ['FastEthernet0/0']  00:33:18
       O           10.0.0.1    110           41        ['3.3.0.2']   ['FastEthernet0/0']  00:32:50
       O*          0.0.0.0/0   110           1         ['3.3.0.2']   ['FastEthernet0/0']  00:32:5
```
for to avoid collection errors in the list of **nexthopIps** change the line for
`^[A-Zio]\*?\s -> Continue.Record`

I've tested the attached example file and the ones commented out in the template file.

Tomorrow I will test the proposed template in the container with suzieq.
[proposed_iosxe_show_route.tfsm.txt](https://github.com/netenglabs/suzieq/files/7124884/proposed_iosxe_show_route.tfsm.txt)

**Comment by aegiacometti** [comment]
Just tested in the container everything looks fine now. All external routes and candidates are here.
@ddutt this is what we chat today in Slack.... please review if it look OK I can do the PR

**Comment by ddutt** [comment]
This all looks good, please issue a PR on the file, @aegiacometti. Thank you. Sorry for the delay in responding. I was caught up in some other  deliverables.

**Comment by aegiacometti** [comment]
Thanks, @ddutt no problem. I'm working on the second issue #415, since it is the same file I will try to do it all together.
I can't stop thinking "life is too short to learn regEx" ;)
