### ISSUE TITLE
Add snapshot mode

### ISSUE THREAD

**Issue by ddutt** [netenglabs/suzieq#429]
**Is your feature request related to a problem? Please describe.**
Today, when the user needs to run suzieq poller just once to gather data, say for network validation, they have a more complex workflow to execute. They have to first run the poller with --run-once=gather option followed by another run of suzieq poller with -i option on the directory the gather was done.

It'd be useful to add a mode called --snapshot that takes the option of running once but writing to parquet directly thereby avoiding the two-step workflow described above. 

It'd be even more useful if the snapshot mode could take a timeout parameter to try executing the command exactly once for each host in the inventory, but add a timeout to give up trying.

**Describe the solution you'd like**
--run-once=gather was a option addded to Suzieq to make it easier for the dev team to support poller parsing issues in the field, and to develop reproducible data for tests. 

**Additional context**

**Comment by ton31337** [comment]
This would be absolutely cool because at the moment we definitely use `--run-once` and immediately `sq-poller` afterward. It's kinda OK, but would be better if handled internally by Suzieq.
