### ISSUE TITLE
pip suzieq==0.15.0 doesn't specify correct dependencies

### ISSUE THREAD

**Issue by LumirH** [netenglabs/suzieq#430]
SuzieQ Pypi module doesn't specify all required dependencies. This is in my opinion unlucky and complicates the installation of suzieq using PIP. 

### How to reproduce:

``

FROM python:3.7.9-slim-buster

RUN apt-get update && \
    apt-get install vim curl -y && \
    pip3 install --upgrade pip build

RUN mkdir -p /suzieq/
WORKDIR /suzieq

RUN ls /suzieq
RUN pip install suzieq==0.15.0

``

### build 

Collecting six>=1.4.1
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting pycparser
  Downloading pycparser-2.20-py2.py3-none-any.whl (112 kB)
Collecting regex!=2019.02.19,!=2021.8.27
  Downloading regex-2021.9.30-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (747 kB)
**Collecting tzlocal
  Downloading tzlocal-3.0-py3-none-any.whl (16 kB)**
Collecting text-unidecode==1.3

During runtime suzieq crashes with the error below. 

Traceback (most recent call last):
  File "/usr/local/bin/sq-poller", line 8, in <module>
    sys.exit(poller_main())
  File "/usr/local/lib/python3.7/site-packages/suzieq/poller/sq_poller.py", line 454, in poller_main
    cfg = load_sq_config(config_file=userargs.config)
  File "/usr/local/lib/python3.7/site-packages/suzieq/utils.py", line 135, in load_sq_config
    error_str = validate_sq_config(cfg)
  File "/usr/local/lib/python3.7/site-packages/suzieq/utils.py", line 96, in validate_sq_config
    def_tz = get_localzone().zone
AttributeError: 'backports.zoneinfo.ZoneInfo' object has no attribute 'zone'

### Solution
**Solution is to manually specify tzlocal version to 2.1.**

**Comment by ddutt** [comment]
Also add colorama fix to the PyPi package

**Comment by ddutt** [comment]
Fixed with commit b5e40cc8d83f9e5e8b6e595245ddf74cfb4f808c and a8a5e65601298ffe93f83d6271cfd1e0a69e930e
