### ISSUE TITLE
netbox inventory source ssl_verify=False option

### ISSUE THREAD

**Issue by protonjhow** [netenglabs/suzieq#541]
Using the new inventory format against netbox, in my new v3 installation http redirects to https by default with a self signed cert. Can we add an option for `ssl_verify: False` in the inventory file?

I tested a hack adding ssl_verify=False at the end of the get in this line, and it seemed to work:
https://github.com/netenglabs/suzieq/blob/92c92ac61618f84a3c6efdc7110c237d6ebd845e/suzieq/poller/controller/source/netbox.py#L154

**Comment by ddutt** [comment]
Fixed via commit 1f34481cffed73d145f761b34cf4db69d134e023
