### ISSUE TITLE
sqPoller show command output definitions

### ISSUE THREAD

**Issue by abemarji** [netenglabs/suzieq#566]
Looking for additional information on the numbers reported in the output.   

As an example, for the device 'Status' Column shows various numbers (14, 404, 0, etc) looking for definitions on what those numbers mean.

For the Values results in columns,  where it has 3 numbers, my understanding they represent min, max, median.  

Also,  A full description of the column headers would be helpful.

**Comment by ddutt** [comment]
This will be fixed along with the issue pointed to by #590.
