### ISSUE TITLE
Support for "first-seen" / "last-seen" timestamp

### ISSUE THREAD

**Issue by LumirH** [netenglabs/suzieq#573]
I believe SuzieQ needs to store not only timestamp when new record was created, but also timestamp when the record was last updated. 

I will demonstrate this on "network find" API, but the problem is generic. Lets assume this method/API call:

root> network find address="10.1.1.1" view=all format=markdown
|    | namespace   | hostname               | vrf     | ipAddress   |   vlan | macaddr           | ifname                  | bondMembers   | type   | l2miss   | timestamp                        |
|---:|:------------|:-----------------------|:--------|:------------|-------:|:------------------|:------------------------|:--------------|:-------|:---------|:---------------------------------|
|  0 | site | router1 | default | 10.1.1.1 |      0 | cc:7f:76:54:5f:33 | GigabitEthernet0/1/3 |               | routed | False    | 2022-01-13 15:40:03.817000+00:00 |
|  1 | site     | router2 | default | 10.1.1.1 |      0 | cc:7f:76:54:34:21 | GigabitEthernet0/1/3 |               | routed | False    | 2022-01-18 16:44:16.415000+00:00 |

From this output, I can say following facts about the network:
- On 13th January, IP address 10.1.1.1 was "seen" on router1 port GigabitEthernet0/1/3
- On 18th January, IP address 10.1.1.1 was "seen" to router2 port GigabitEthernet0/1/3

I would be interested in additional information:
- Is IP address 10.1.1.1 still available on router2 ? When it was last seen on this port ? How old is the information that I see in this output ? 
- Was IP address 10.1.1.1 connected to router1 for example on 15th January ? (device with this IP address could have been disconnected from the network for example on 15th January and reconnected on 18th January to router2)

**Proposed solution:**
Store two timestamps. First will be updated when record has been first created (first-seen), second timestamp would be updated every time when you re-discover the same information.

**Comment by ddutt** [comment]
This is fixed without the suggestion. Here is a sample output seen in 0.17.1:
```
ddutt> network find start-time='4 Apr 2022, 11 pm' end-time='5 Apr 2022, 5:30 am' address='172.16.2.201'
  active namespace hostname       vrf     ipAddress vlan            macaddr  ifname bondMembers     type  l2miss                        timestamp
0      +      demo   leaf03  evpn-vrf  172.16.2.201   20  fe:95:fd:1a:1e:2e  bond01        swp3  bridged   False 2022-04-04 23:18:30.769000-07:00
1      +      demo   leaf04  evpn-vrf  172.16.2.201   20  fe:95:fd:1a:1e:2e  bond01        swp3  bridged   False 2022-04-04 23:18:31.820000-07:00
2      -      demo   leaf04         -  172.16.2.201    -  fe:95:fd:1a:1e:2e  Vlan20           -  bridged   False 2022-04-05 05:04:41.575000-07:00
3      -      demo   leaf03         -  172.16.2.201    -  fe:95:fd:1a:1e:2e  Vlan20           -  bridged   False 2022-04-05 05:04:41.911000-07:00```
