### ISSUE TITLE
Add Netbox token as environment variable

### ISSUE THREAD

**Issue by rickdonato** [netenglabs/suzieq#579]
**Is your feature request related to a problem? Please describe.**
In 0.16.0, you are unable to add the token within sources as an environment variable. However, this is a security issue when adding your inventory to source control. 

**Describe the solution you'd like**
Ideally, it would be great to have all configuration options and inventory settings available via environment variables.
Grafana uses this approach and it works really well. I also think leveraging something like Pydantic may take the heavy lifting out of exposing all the different settings for you. Just a thought.

**Comment by ddutt** [comment]
Fixed in 0.17.1 via commit 2f8fd95a1279147e2d170e738f6ad5064338f4a3
