### ISSUE TITLE
sqPoller show's metrics need doc fixes, one improvement suggestion

### ISSUE THREAD

**Issue by LumirH** [netenglabs/suzieq#582]
sqPoller documentation says that gatherTime, totalTime, rxBytes are "Min, max, median of time taken to get data, for this 5-min interval".
This is not correct. 

1) if polling period > 5 minutes, stats are gathered only once per every polling period. 
This is cosmetic problem -- but would be good to get it updated in the documentation. 

2) Min, Max values are never reset -- they are absolute values since the beginning of the polling. 
Evidence is below:

root> sqPoller show start-time=1643108040000  end-time=1643194440000 hostname=leaf101-N93180YC-EX service=macs
   namespace             hostname service  status                  gatherTime                    totalTime  ...                  wrQsize        nodeQsize                rxBytes pollExcdPeriodCount  active                        timestamp
0    brnolab  leaf101-N93180YC-EX    macs       0   [480.0, 6161.0, 889.2943]    [481.0, 6162.0, 897.9588]  ...         [0.0, 1.0, 0.25]  [0.0, 8.0, 0.0]  [425.0, 425.0, 425.0]                   0    True 2022-01-25 11:24:32.939000+00:00
1    brnolab  leaf101-N93180YC-EX    macs       0  [480.0, 6161.0, 700.64716]    [481.0, 6162.0, 705.4794]  ...        [0.0, 1.0, 0.125]  [0.0, 8.0, 0.0]  [425.0, 425.0, 425.0]                   0    True 2022-01-25 12:24:33.461000+00:00
2    brnolab  leaf101-N93180YC-EX    macs       0  [480.0, 6161.0, 661.82355]    [481.0, 6162.0, 664.7397]  ...       [0.0, 1.0, 0.0625]  [0.0, 8.0, 0.0]  [425.0, 425.0, 425.0]                   0    True 2022-01-25 13:24:34.091000+00:00
3    brnolab  leaf101-N93180YC-EX    macs       0   [480.0, 6161.0, 571.9118]    [481.0, 6162.0, 573.8699]  ...      [0.0, 1.0, 0.03125]  [0.0, 8.0, 0.0]  [425.0, 425.0, 425.0]                   0    True 2022-01-25 14:24:34.574000+00:00

**Comment by ddutt** [comment]
@LumirH I changed the title of the bug to reflect the real point that I think you're making. Please let me know if this isn't right

**Comment by ddutt** [comment]
Fixed in 0.17.1 via commits 134e0ce4b0203697dca5f4a2723b263dc21e071d, and ea59c64f04ad90720e9fc078793f9dc6f2697792
