### ISSUE TITLE
Expose Security Settings in Config via ENV

### ISSUE THREAD

**Issue by rickdonato** [netenglabs/suzieq#587]
**Is your feature request related to a problem? Please describe.**
The API KEY is hardcoded within the config file. Making it difficult to source control the file.

**Describe the solution you'd like**
Any security settings in the config file exposed using env variables.

**Comment by ddutt** [comment]
@LucaNicosia I believe you fixed this a long time ago.

**Comment by rickdonato** [comment]
@ddutt @LucaNicosia Thanks. Can you confirm how I reference an env variable from within the config file.

**Comment by ddutt** [comment]
Fixed via commit 06507652eac6888ea808cd574fb0c0f9906fc42e
