### ISSUE TITLE
NX-OS driver should not rely on "feature bash-shell"

### ISSUE THREAD

**Issue by LumirH** [netenglabs/suzieq#591]
I think it's better to avoid dependency on "feature bash-shell" on nxos devices. 
Many deployments doesn't have this feature enabled due to security concerns. 

  nxos:
    version: all
    command: run bash top -bn 1 | head -17

This command can be replaced using for example  show processes cpu".

**Comment by ddutt** [comment]
@claudious96 Just remove support for nxos by removing run bash in the commands for now. We can replace with the command mentioned once we start supporting topcpu, topmem etc. Check all config/*.yml for run bash against nxos.

**Comment by ddutt** [comment]
This issue has been fixed via commit 6e1666b198fd9237ba9ceb9f75fd4fe3afc7f40a
