### ISSUE TITLE
Python Library Config for Remote API

### ISSUE THREAD

**Issue by rickdonato** [netenglabs/suzieq#595]
**Describe the bug**
When setting the Python library to use a config file for pulling data from a remote API (shown below) I get an empty result. When querying the tables. When looking at the `interface_tbl` object, it appears the incorrect remote rest ip/port has been set.
```
interface_tbl = get_sqobject("interfaces")(
    config_file="suzieq/suzieq-cfg.client.yml")
```

**Comment by ddutt** [comment]
This has been fixed in 0.17.1 by various commits such as 06507652eac6888ea808cd574fb0c0f9906fc42e, b6ca2131d33d192f43b11a5107bd1f0b10315fe9 and f9766fc2fecc7d6170b5db82d4565152e8f485b2.
