### ISSUE TITLE
Cli, We are inconsistent with what we return for errors

### ISSUE THREAD

**Issue by jopietsch** [netenglabs/suzieq#61]
if there is an error in the CLI we return different things. Sometimes we print an error and return an empty dataframe, sometimes we return an exception, sometimes we return a dataframe with an error message in it.

**Comment by ddutt** [comment]
This has been addressed in many cases, but its hard to know if its been addressed in all without tests to look for. Leaving this open until we add tests

**Comment by ddutt** [comment]
Closing as even more consistency has been added in 0.16.0 alpha. If needed, we can create new issues with specific inconsistencies
