### ISSUE TITLE
DevConfig returns no output when running via remote DB

### ISSUE THREAD

**Issue by rickdonato** [netenglabs/suzieq#639]
**Describe the bug**
DevConfig doesn't return output when running via the remote DB. Works locally.

**To Reproduce**
```
root> devconfig show
```

**Attach**
TBC

 **Expected behavior**
TBC

**Screenshots**
TBC

**Additional context**
Environment from which this is occurring in:
* remote cli is being used
* correct port setting applied via "set rest-server-port=443"
* can successfully query other tables. For example "device show"

**Local DB works, but remote dosn't**

**Comment by ddutt** [comment]
Fixed along with other issues associated with remote DB
