### ISSUE TITLE
[Feature]: add the ability to group devices in "sites"

### ISSUE THREAD

**Issue by anubisg1** [netenglabs/suzieq#706]
### Suzieq version

0.17.1

### Install Type

container

### Feature type

Extend sq-poller

### Use case

a customer has multiple sites, for example a DC in France and a DC in Italy.
The same customer might also have branch offices in multuple locations.

such user would like to see each site separate from the rest as things like VLAN numbers might overlap

### Proposed functionality/solution

Give the ability to a user to group devices in sites.
Asserts should only be applied to a single site.
correlation between sites should also be displayed.

Notice that a site is different from a namespace, where a namespace today provides full separation of devices and likely it's meant to be extended into the basic of RBAC to provide isolation between multiple customers in a multi-tenant suzieq installation

**Comment by ryanmerolle** [comment]
This would be great.  I currently use namespaces but would prefer a better way.
