### ISSUE TITLE
[Feature]: provide RBAC functionalities

### ISSUE THREAD

**Issue by anubisg1** [netenglabs/suzieq#707]
### Suzieq version

0.17.1

### Install Type

container

### Feature type

other

### Use case

provide RBAC functionalities.
provide the ability to have users with different roles and permissions.

A typical use case is to have multiple namespaces and a user needs to be give RO or RW access to some tables (or all tables) in 1 or more namespaces

### Proposed functionality/solution

this might require more work than expected.
there are multiple options , like just providing users to the UI but that would be a parial solution not long term.

functionality wise, it would work like so:

1) there are permissions defined like:
    - mac_read
    - route_read
    - network_read
    - read_all
    - read_write

a read_write user is a user able to modify the inventory file

2) permissions are grouped in roles. roles can be defined by the admin user as per their need, for example:
    - role server administrator might have "mac_read" , "network_read" but NOT have "devices_read" 

3) the roles are then binded to a namespace and given to a user

Assuming that there are 2 namespaces, customer1 and customer2, then the following could be achieved:

user 1:
- customer1.admin    (admin is a role with permission read_all and read_write)
- customer2.server_admin ( server_admin is a role with mac_read and netword_read permission)

user 2:
- customer2.customer (customer is a role with permission path_read, network_read)

  
In my view, some restructure of suzieq components could be necessary. Specifically those permission in my view need to be passed from the frontend to the backend in every request , the backend should validate the permissions and enforce them.

a proper front-end / back-end architecture might also be necessary to created, rather than having every single component reading directly from a data directory and rebuild the logic in Web UI, Rest and CLI.

Finally, permissions should be pre-defined, roles could be defined statically in a configuration file like the namespaces, but users must be created dynamically and have such roles assigned to them via the UI.
Users could be statically defined or in the best possible solution taken from an LDAP server. 

In my opinion, a new dedicated micro service handling Rbac could be the better way to proceed.

**Comment by ryanmerolle** [comment]
This would be a good enterprise feature.

**Comment by anubisg1** [comment]
move to enterprise tree
