### ISSUE TITLE
textfsm templates missing test data

### ISSUE THREAD

**Issue by jopietsch** [netenglabs/suzieq#71]
these are the templates that don't have data so that we can automatically test them
linux_meminfo
system
eos_showver
ifCounters

**Comment by zxiiro** [comment]
I opened #447 to add a test for linux_meminfo. I have no idea where the other 3 items comes from so unfortunately can't help with those.

**Comment by ddutt** [comment]
We have too many textfsm samples now that don't have a specific output. This is because we often lack the appropriate data.
