### ISSUE TITLE
[Bug]: wrong interface description for sub interfaces in junos 

### ISSUE THREAD

**Issue by mmarin11** [netenglabs/suzieq#873]
### Suzieq version

0.20.1

### Install Type

hand deployed python

### Python version

3.8

### Impacted component

other

### Steps to Reproduce

1.- Query interfaces interface show hostname=X.X.X.X columns='hostname ifname description'

2.- Interface descriptions of sub interfaces use the interface of main interface. Below an example. All subinterfaces have the description of ae4

![image](https://user-images.githubusercontent.com/40378669/227822134-892f3bd1-aac5-49d6-820e-f17bcb3f5edc.png)

### Expected Behavior

Sub interfaces should have different descriptions

### Observed Behavior

NA

**Comment by ddutt** [comment]
Fixed with release 0.21.0
