### ISSUE TITLE
[Docs]: FileSystem stated as supported for nxos, textfsm config file is not configured for nxos

### ISSUE THREAD

**Issue by heathdbrown** [netenglabs/suzieq#899]
### Change Type

Correction

### Area

Functionality/features

### Proposed Changes

In the tables.md the following line 

https://github.com/netenglabs/suzieq/blob/fe92eec3a2b1cca9622d1f03e7f7471ff3240c55/docs/tables.md?plain=1#L15

should be updated to state that nxos is not supported based on the textfsm configuration.

OR 

The textfsm configuration should be updated to support the filesytem for nxos.

https://github.com/netenglabs/suzieq/blob/develop/suzieq/config/fs.yml

**Comment by ddutt** [comment]
Fixed
